import { SideBar } from "@/components/side-bar"
import { ModeToggle } from "@/components/theme-toggle"
import { TranslateToggle } from '@/components/translate-toggle'
import { UserNav } from '@/components/user-nav'
import '@/styles/globals.css'
import type { Metadata } from 'next'
import { getServerSession } from "next-auth"
import { NextIntlClientProvider } from 'next-intl'
import { Inter } from 'next/font/google'
import Link from 'next/link'
import { authOptions } from "../api/auth/[...nextauth]/route"
import { ThemeProvider } from "@/components/theme-provider"


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode
  params: { lang: string}
}) {
  const session = await getServerSession(authOptions)

  return (
    <html lang={params.lang} suppressHydrationWarning>
      <body className={inter.className}>
        <NextIntlClientProvider>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="border-b">
            <div className="flex h-16 items-center px-4">
              <SideBar/>
              <Link href="/">Dashboard</Link>
              <div className="ml-auto flex items-center space-x-4">
                <ModeToggle/>
                <TranslateToggle/>
                <UserNav session={session}/>
              </div>
            </div>
          </div>
          {children}
        </ThemeProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  )
}
